name: CI

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup-node
      - run: npm run lint

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup-node
      - run: npm run typecheck

  test:
    runs-on: ubuntu-latest
    services:
      postgres-test:
        image: postgres:17
        env:
          POSTGRES_DB: battlecatsdle_test
          POSTGRES_USER: battlecatsdle_test
          POSTGRES_PASSWORD: battlecatsdle_test
        ports:
          - 5433:5432
        options: >-
          --health-cmd="pg_isready -U battlecatsdle_test"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=10
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup-node
      - run: cp .env.ci .env
      - run: node ace generate:key
      - run: npm run test
